//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVRS_Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LVRSMEMBERSEntities : DbContext
    {
        public LVRSMEMBERSEntities()
            : base("name=LVRSMEMBERSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<applicationStatu> applicationStatus { get; set; }
        public virtual DbSet<applicationStatusType> applicationStatusTypes { get; set; }
        public virtual DbSet<award> awards { get; set; }
        public virtual DbSet<awardType> awardTypes { get; set; }
        public virtual DbSet<background> backgrounds { get; set; }
        public virtual DbSet<birthday> birthdays { get; set; }
        public virtual DbSet<countyNumber> countyNumbers { get; set; }
        public virtual DbSet<dropped> droppeds { get; set; }
        public virtual DbSet<dualMember> dualMembers { get; set; }
        public virtual DbSet<email> emails { get; set; }
        public virtual DbSet<finalJoinStatu> finalJoinStatus { get; set; }
        public virtual DbSet<fingerprint> fingerprints { get; set; }
        public virtual DbSet<initialJoinStatu> initialJoinStatus { get; set; }
        public virtual DbSet<interviewContact> interviewContacts { get; set; }
        public virtual DbSet<interviewSchedule> interviewSchedules { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<jobType> jobTypes { get; set; }
        public virtual DbSet<jotForm> jotForms { get; set; }
        public virtual DbSet<leaveStatu> leaveStatus { get; set; }
        public virtual DbSet<leaveType> leaveTypes { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<phone> phones { get; set; }
        public virtual DbSet<physicalPassed> physicalPasseds { get; set; }
        public virtual DbSet<physicalSchedule> physicalSchedules { get; set; }
        public virtual DbSet<probation> probations { get; set; }
        public virtual DbSet<resigned> resigneds { get; set; }
        public virtual DbSet<rideAlong> rideAlongs { get; set; }
        public virtual DbSet<statusChange> statusChanges { get; set; }
        public virtual DbSet<statusType> statusTypes { get; set; }
        public virtual DbSet<vr> vrs { get; set; }
    }
}
